<template>
  <video
    crossorigin="true"
    playsinline
    poster="../video/poster2.png"
    src="../video/phone-vital-header.mp4"
    muted
    loop
    autoplay
    preload="metadata"
  />
</template>
